import Head from 'next/head'
import Link from 'next/link';
import { Container,Row, Col, Button, Card } from 'react-bootstrap';


export default function Home() {
  return (
    <>
      <Head>
        <title>Loadmore/Infinite Scroll</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className='py-5'>
        <div className='text-center'>
          <h1>NextJS/ReactJS Load more and infinite scroll</h1>
          <p><a href='https://github.com/Jaironlanda'>GitHub</a> | <a href='https://dummyjson.com'>API</a></p>
        </div>
        <Row>
          <Col sm={6} className={'p-3'}>
            <Card>
              <Card.Body>
                <Card.Img variant="top" src={'public/example/loadmore-example.gif'}/>
                <Card.Title>Load More Example</Card.Title>
                <Card.Text>Basic Load more Button in ReactJS/NextJs</Card.Text>
                <Link href={'/loadmore'} className={'btn btn-primary'}>View</Link>
              </Card.Body>
            </Card>
          </Col>
          <Col sm={6} className={'p-3'}>
            <Card>
              <Card.Body>
              <Card.Img variant="top" src={'public/example/infinitescroll-example.gif'}/>
                <Card.Title>infinite scroll</Card.Title>
                <Card.Text>Basic infinite scroll in ReactJS/NextJs</Card.Text>
                <Link href={'/autoloadmore'} className={'btn btn-primary'}>View</Link>
              </Card.Body>
            </Card>
          </Col>
        </Row>
        
      </Container>
    </>
  )
}
